### ISSUE TITLE
python run.py

### ISSUE THREAD

**Issue by Antwnina** [nicolewhite/neo4j-blog-flask#15]
(venv) antonina@antonina-HP-Pavilion-g6-Notebook-PC:~/neo4j-flask$ python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from blog import app
  File "/home/antonina/neo4j-flask/blog/__init__.py", line 1, in <module>
    from .views import app
  File "/home/antonina/neo4j-flask/blog/views.py", line 1, in <module>
    from .models import User, get_todays_recent_posts
  File "/home/antonina/neo4j-flask/blog/models.py", line 2, in <module>
    from passlib.hash import bcrypt
ImportError: No module named passlib.hash

**Comment by Antwnina** [comment]
so the whole point were the variables
export NEO4J_USERNAME=username
export NEO4J_PASSWORD=password
