### ISSUE TITLE
ImportError: cannot import name 'ForkingMixIn' - Python 3.6 

### ISSUE THREAD

**Issue by ryancollingwood** [nicolewhite/neo4j-blog-flask#19]
Environment: 
- Python 3.6
- Windows 10

**Problem**
Console output
````
PS D:\Projects\neo4j-flask> python run.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\werkzeug\serving.py", line 65, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app.run(host='0.0.0.0', port=port)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 828, in run
    from werkzeug.serving import run_simple
  File "C:\ProgramData\Anaconda3\lib\site-packages\werkzeug\serving.py", line 68, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn'
PS D:\Projects\neo4j-flask> pip install -U werkzeug
````
**What Worked for Me**

As per: https://stackoverflow.com/a/39214538/2805700

> This is fixed as of Werkzeug 0.11.15. Make sure you have installed the latest version of Werkzeug. pip install -U werkzeug.

So I ran `pip install -U werkzeug`

Updated requirements.txt should to Werkzeug>=0.14.10

**Comment by Shashank200** [comment]
u should install a new version of  werkzeug
Pycharm->defaultsetting->+ at right top->then search werkzeug 
or pip install -U werkzeug
